{{- if and .Values.imageCredentials.username .Values.imageCredentials.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "php-demo.registrySecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "php-demo.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "php-demo.dockerconfigjson" . | b64enc }}
{{- end }}
