apiVersion: v1
kind: Secret
metadata:
  name: {{ include "php-demo.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "php-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.auth.rootPassword | required "mariadb.auth.rootPassword is required" | quote }}
  MARIADB_DATABASE:      {{ .Values.mariadb.auth.database | quote }}
  MARIADB_USER:          {{ .Values.mariadb.auth.username | quote }}
  MARIADB_PASSWORD:      {{ .Values.mariadb.auth.password | required "mariadb.auth.password is required" | quote }}
