apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "php-demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "php-demo.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- if and .Values.imageCredentials.username .Values.imageCredentials.password }}
imagePullSecrets:
  - name: {{ include "php-demo.registrySecretName" . }}
{{- end }}
