apiVersion: v1
kind: Service
metadata:
  name: {{ include "php-demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "php-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "php-demo.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
